#!/bin/bash -ex
# vim: set filetype=sh :

# This script installs magento

source /app.configure

sudo -u "${php_user}" /bin/bash -ex << END_OF_SUDO
cd "${php_home}"

echo Downloading Magento
# curl -s -L https://github.com/magento/magento2/releases/latest \
#     | egrep -o '/magento/magento2/archive/.*tar\.gz' \
#     | wget --base=http://github.com/ -i - -O /tmp/magento.tar.gz

curl -s -L https://github.com/OpenMage/magento-mirror/releases/latest \
    | egrep -o 'OpenMage/magento-mirror/archive/.*tar\.gz' | head -1 \
    | wget --base=http://github.com/ -i - -O /tmp/magento.tar.gz
tar -zxf /tmp/magento.tar.gz --strip-components=1

echo Installing Magento
php -f install.php -- \
  --license_agreement_accepted "yes" \
  --locale $locale \
  --timezone 'MST7MDT' \
  --default_currency 'USD' \
  --db_host $db_host \
  --db_name $db_name \
  --db_user $db_user \
  --db_pass $db_pass \
  --url $app_url \
  --skip_url_validation 'yes' \
  --use_rewrites 'yes' \
  --use_secure 'no' \
  --secure_base_url "$app_url" \
  --use_secure_admin 'no' \
  --admin_firstname $admin_user \
  --admin_lastname $admin_user \
  --admin_email $admin_email \
  --admin_username $admin_user \
  --admin_password $admin_pass

END_OF_SUDO

# Run project-specific installation commands
s
# Start the app
source /app.start
